name: 自动采集

on:
  workflow_dispatch:
  schedule:
    - cron: '04 0/2 * * *'
  watch:
    types: [started]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存  
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r requirements.txt
    - name: 执行任务

      run: |
        python main.py

          
    - name: 提交更改
      run: |                 
         git config --local user.email "ldir92664@163.com"
         git config --local user.name "ldir92664"
         git add subscribe/clash.yml
         git add subscribe/clash-pro.yml
         git add subscribe/ednovas.design.yml
         git add subscribe/imyaoxp-getclash.yml
         git add subscribe/Top-FreeProxies.yml
         git add subscribe/hellopool.herokuapp.com.yml
         git add subscribe/origamiboy.herokuapp.com.yml
         git add subscribe/README.md
         git commit -m "更新订阅链接"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
         ## github_token: ${{ secrets.TOKEN }}
         branch: main
